controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_login:
    path: /api/v1/auth/login
api_refresh_token:
    path: /api/v1/auth/refresh
